version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/flashcard-app

permissions:
  - object: /home/ec2-user/flashcard-app
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ec2-user
      
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
      
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user