version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci
      - cd server && npm ci && cd ..
      
  build:
    commands:
      - echo Building server...
      - cd server && npm run build && cd ..
      - echo Building React app...
      - npm run build
      
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*
    - server/node_modules/**/*
    - .git/**/*
    - .gitignore
    - README.md
    
cache:
  paths:
    - 'node_modules/**/*'
    - 'server/node_modules/**/*'