version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js 18
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - cd server
      - npm install
      - cd ..
      
  build:
    commands:
      - echo Building server TypeScript...
      - cd server
      - npx tsc
      - cd ..
      - echo Building React app...
      - npm run build
      - echo Verifying builds...
      - ls -la server/dist/
      - ls -la build/
      
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'build/**/*'
    - 'server/dist/**/*'
    - 'server/node_modules/**/*'
    - 'server/package*.json'
    - 'appspec.yml'
    - 'scripts/**/*'
    
cache:
  paths:
    - 'node_modules/**/*'
    - 'server/node_modules/**/*'