name: Deploy to AWS EC2

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd server && npm ci && cd ..

    - name: Build application
      run: |
        # Build server
        cd server && npm run build && cd ..
        # Build React app
        npm run build
      env:
        REACT_APP_WS_URL: ${{ secrets.REACT_APP_WS_URL }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_PIPECAT_ROOM_URL: ${{ secrets.REACT_APP_PIPECAT_ROOM_URL }}
        REACT_APP_PIPECAT_AGENT_URL: ${{ secrets.REACT_APP_PIPECAT_AGENT_URL }}
        REACT_APP_PIPECAT_API_KEY: ${{ secrets.REACT_APP_PIPECAT_API_KEY }}

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Stop current application
          sudo systemctl stop flashcard-app || true
          
          # Pull latest code
          cd /home/ec2-user/flashcard-app
          git pull origin master
          
          # Install dependencies
          npm ci
          cd server && npm ci && cd ..
          
          # Build application
          cd server && npm run build && cd ..
          npm run build
          
          # Restart application
          sudo systemctl start flashcard-app
          
          # Health check
          sleep 5
          curl -f http://localhost:8080/health || exit 1